x = float(input("Nhap gia tri cua x: "))
p = (x + 1 == 2)
x2, y = map(float, input("Nhap gia tri cua x2 va y: ").split())
z = float(input("Nhap gia tri cua z: "))
q = (x2 + y == z)
print(f"Menh de 1 goc: {p}")
print(f"Menh de 2 goc: {q}")
dao_p = (p == True) and (x + 1 == 2)
nghich_dao_p = (x + 1 != 2 and p == False)
phan_dao_p = (p == False and x + 1 != 2)
dao_q = (q == True) and (x2 + y == z)
nghich_dao_q = (x2 + y != z and q == False)
phan_dao_q = (q == False and x2 + y != z)
print("MENH DE 1")
print(f"Dao: {dao_p}")
print(f"Nghịch đảo: {nghich_dao_p}")
print(f"Phản đảo: {phan_dao_p}")
print("MENH DE 2")
print(f"Dao: {dao_q}")
print(f"Nghịch đảo: {nghich_dao_q}")
print(f"Phản đảo: {phan_dao_q}")