x=int(input('x= '))
y=int(input('y= '))
z=int(input('z= '))
p=(x+1==2)
q=(x+y==z)
print("p and q ", p and q)
print("p or q ", p or q)
print("not p", not p)
print("not q", not q)
print("p xor q ", p ^ q)