import networkx as nx
from Node2Vec import Node2Vec

# generate N2V embeddings
book_graph = nx.read_gml('polbooks.gml') # loads graph data from a GML file into a NetworkX graph object
node2vec = Node2Vec(book_graph, dimensions = 64, walk_length = 30, num_walks = 200, workers = 4) # initialize N2V model with specified parameters for input graph
model = node2vec.fit(window = 10, min_count = 1, batch_words = 4) # train N2V model
embeddings = {str(node) : model.wv[str(node)] for node in gml_graph.nodes()} # extract & store node embeddings generated by N2V model in a dictionary

node_embedding = model.wv['Losing Bin Laden']
print(node_embedding)

# visualize embeddings using UMAP
node_embedding = [embeddings[str(node)] for node in gml_graph.nodes()] # transform embeding into a list of vectors for UMAP
node_embedding_array = np.array(node_embedding)

umap_model = umap.UMAP(n_neighbors = 15, min_dist = 0.1, n_components = 2, random_state = 42)
umap_features = umap_model.fit_transform(node_embedding_array) # initialize & fit UMAP

plt.scatter(umap_features[:, 0], umap_features[:, 1], color = node_colors, alpha = 0.7) # plots the nodes with UMAP embeddings & color by their value

# visualizing 2D N2V embeddings without t-SNE
node2vec = Node2Vec(gml_graph, dimensions = 2, walk_length = 30, num_walks = 200, workers = 4) # initialize N2V with 2D embeddings for visualization
model = node2vec.fit(window = 10, min_count = 1, batch_words = 4) # train N2V model with specified window & walks settings
embeddings_2D = {str(node) : model.wv[str(node)] for node in gml_graph.nodes()} # map nodes to their 2D embeddings
points = np.array([embeddings_2D[node] for node in gml_graph.nodes()]) # form an array of 2D points for each node's embedding
plt.scatter(points[:, 0], points[:, 1], color = node_colors, alpha = 0.7) # plot 2D embeddings with specified node colors

'''
nqbh@nqbh:~/advanced_STEM_beyond/graph_neural_network/Python$ python3 generate_N2V_embedding.py 
Traceback (most recent call last):
  File "/home/nqbh/advanced_STEM_beyond/graph_neural_network/Python/generate_N2V_embedding.py", line 1, in <module>
    import NetworkX as nx
ModuleNotFoundError: No module named 'NetworkX'
'''